[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
strategy_engine = "7Xnzrm7QHgLwANg78gBg55DZ8eEaxXzzvf9BSMtKdUcT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
